server:
  http:
    listen_addr: ':8127'
    # allowed_networks: ['127.0.0.0/24', '192.168.9.0/24']
# Разрешить все сети
hack_me_please: true   

users:
  - name: 'admin'
    to_cluster: 'cluster_2S_2R'
    to_user: 'default'
    max_concurrent_queries: 100
    max_execution_time: 30s
    requests_per_minute: 10
    # Allow `CORS` requests for `tabix`.
    allow_cors: true

  - name: 'default'
    to_cluster: 'cluster_2S_2R'
    to_user: 'default'
    # Allow `CORS` requests for `tabix`.
    allow_cors: true
clusters:
  - name: 'cluster_2S_2R'
    nodes:
      [
        'clickhouse-01:8123',
        'clickhouse-02:8123',
        'clickhouse-03:8123',
        'clickhouse-04:8123',
      ]
    users:
      - name: 'default'
